name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: "28.2"
      - uses: conao3/setup-keg@master

      - run: keg install
      - run: keg run build
